### ISSUE TITLE
Báo cáo cá nhân và chấm chéo.

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/INT2208-2-2018#482]
1. Mỗi bạn làm báo cáo tổng kết trong môn học này đã làm các bài tập cá nhân, bài tập nhóm, và tham gia tự học được đến đâu. Báo cáo cần kèm theo minh chứng bằng các url đến tài liệu, thông tin để dễ dàng kiểm tra, xác minh được. Hạn là trong ngày thứ 3 ngày 8/5/2018. Báo cáo được đặt tên là: tongket.md đặt trong thư mục của mỗi người.

2. Mỗi bạn chấm điểm 4 bạn sinh viên ở dưới mình trong danh sách. Các bạn ở cuối danh sách thì quay lên đầu danh sách cho đủ 4 bạn. Các bạn cũng bỏ qua các bạn đã bỏ học, không có bài để chấm, không liên lạc được. Khi chấm, các bạn có thể trao đổi với bạn được chấm đề làm rõ việc tham gia làm bài tập về nhà, bài tập nhóm đến được đến đâu. Các bạn chấm điểm xong ghi điểm vào Excel, đồng thời ghi điểm vào cuối file tongket.md của bạn được chấm. Ghi rõ các thông tin:
   - Người chấm: 
   - Điểm:
   - Nhận xét: 
Hạn cho việc này là thứ 5, ngày 10/5.

**Comment by vuvihi** [comment]
Em thưa thầy, khoá học phải mua mới có chứng chỉ thầy ạ 
![image](https://user-images.githubusercontent.com/32568148/39673342-81e13f9a-5164-11e8-99b3-de54f0be160f.png)

**Comment by truonganhhoang** [comment]
Các em ko cần mua nhé.

**Comment by vuvihi** [comment]
Khoá học của tất cả điều học được duy có phần Final Exam: Verified and Proctored  thì nó không hiện ra gì cả. Chắc do vậy nên không có link chứng chỉ
![image](https://user-images.githubusercontent.com/32568148/39673440-76042fdc-5166-11e8-89a3-d3fb63dfc18b.png)

**Comment by truonganhhoang** [comment]
OK.. vậy các em bỏ qua nếu ko làm đc final exam.

**Comment by tieuconghoa** [comment]
Em chào Thầy a, hiện tại chấm điểm trên googlesheet đang khoá ạ, mong thầy mở để chúng em chấm điểm ạ, em cảm ơn

**Comment by tieuconghoa** [comment]
Em chào Thầy a, hiện tại chấm điểm trên googlesheet đang khoá ạ, mong thầy mở để chúng em chấm điểm ạ, em cảm ơn

**Comment by truonganhhoang** [comment]
Các em comment vào điểm, sau đó điểm sẽ được chuyển vào ô.
