### ISSUE TITLE
Tài liệu ôn tập

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/INT2208-2-2018#940]
Mình đã sửa được một nửa tài liệu khóa học để các em ôn tập:

https://docs.google.com/document/d/1a4i_31R8WBUAnF91syr1FwBpKoAiTY6rEJt1xWjb74M/

Phần còn lại sẽ mất 2-3 hôm nữa. Các em đọc ôn dần phần trên và góp ý (comment) nếu chỗ nào sai, lỗi, hoặc có câu hỏi.

**Comment by truonganhhoang** [comment]
Tài liệu ôn tập về cơ bản đã xong. Các em ôn tập dựa trên link trên, nắm được các kiến thức cơ bản để trả lời trắc nghiệm. Ôn lại các câu hỏi đã có trong [khóa học](https://www.edx.org/course/software-engineering-introduction-ubcx-softeng1x).

**Comment by truonganhhoang** [comment]
Các câu hỏi sẽ chủ yếu dựa trên câu hỏi của [khóa học](https://www.edx.org/course/software-engineering-introduction-ubcx-softeng1x), đã có tài liệu tiếng Việt để ôn. Không thi phần Introduction.

**Comment by DoanThiThoa** [comment]
thầy ơi thầy có thể cấp quyền in tài liệu để bọn em in ra cho dễ học không ạ

**Comment by 16021297** [comment]
Thầy ơi cấu trúc đề thi như nào ạ( có bao nhiêu câu trắc nghiệm và có tự luận không ạ) và lớp mình thi đề chung hay riêng vậy ạ.

**Comment by truonganhhoang** [comment]
tự luận 6 điểm, trắc nghiệm 4 điểm.. mình nộp đề riêng sáng nay rồi.. tài liệu mình đang rà soát thêm, rất mong các bạn góp ý để nó tốt hơn và sau đó in

**Comment by trunghieu2609vn** [comment]
Thầy ơi phần trắc nghiệm vẫn gồm 30 câu như các năm ạ.

**Comment by truonganhhoang** [comment]
ít hơn, nhưng khó hơn và điểm mỗi câu cao hơn.. các em bám sát khóa học trực tuyến thì chắc là sẽ làm được bài tốt.

**Comment by trunghieu2609vn** [comment]
vâng em cám ơn thầy.

**Comment by truonganhhoang** [comment]
hiện đã có điểm thành phần, các bạn xem có kiến nghị gì thì comment vào ô tương ứng hoặc email cho mình.

**Comment by truonganhhoang** [comment]
hiện đã có điểm thành phần, các bạn xem có kiến nghị gì thì comment vào ô tương ứng hoặc email cho mình.

**Comment by trunghieu2609vn** [comment]
thầy ơi cột điểm thành phần màu cam ấy chính là điểm thành phần chốt cuối cùng của bọn e ạ

**Comment by 16021297** [comment]
thầy ơi phần tự luận có dạng giống đề thầy up hay thi phần nào vậy ạ

**Comment by truonganhhoang** [comment]
tự luận ko giống đề năm trước, tất cả dựa trên khóa học MOOC hết nhé..

**Comment by truonganhhoang** [comment]
https://github.com/truonganhhoang/INT2208-4-2018/issues/457

**Comment by trunghieu2609vn** [comment]
Thầy ơi phần SEMAT có cần ôn không ạ

**Comment by truonganhhoang** [comment]
ko nhé.

**Comment by TongThanhSon** [comment]
Em thưa thầy thầy xem lại giúp em điểm tự học của Tống Thanh Sơn
sao chỉ được có 1 ạ ?


2018-05-27 19:40 GMT+07:00 Hoàng Trương <notifications@github.com>:

**Comment by truonganhhoang** [comment]
do phần công thức bị nhầm.. mình sửa lại rồi nhé.
